markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 5
language: 'en-uk'

# Website info
name: 'YETI'
description: "Your Everyday Threat Intelligence"

# Authors
authors:
    tomchop:
        name: Thomas Chopitea
        bio: APT-buster. Incident handler, lethal forensicator, malware analyst. Sifting through the CTF of life.
        location: Zurich, Switzerland
        url: http://tomchop.me/
        image: assets/images/avatar_tomchop.png
        twitter: tomchop_
    gael:
        name: Gael Muller
        bio: Blue team member. The nicest one.
        location: Versailles, France
        image: assets/images/avatar_gael.png
        twitter: GaelMuller

google_analytics: UA-93509714-1

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Permalinks
permalink: /:title


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml

excerpt_separator: <!--more-->
